name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Miniconda Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: test-env
        auto-activate-base: false
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 cpuonly -c pytorch
        pip install "MKL==2024.0.0" "setuptools<80.9.0" wheel
        pip install --no-build-isolation mmcv==1.7.2
        if [ -f setup.py ]; then pip install -e .; fi
        if [ -d g2tm ]; then if [ -f g2tm/setup.py ]; then cd g2tm/ && pip install -e . && cd ../; fi; fi
    - name: Install Pylint
      shell: bash -l {0}
      run: |
        pip install pylint
    - name: Analysing the code with Pylint
      shell: bash -l {0}
      run: |
        pylint $(git ls-files '*.py') --disable=E1120,I1101,R0902,R0912,R0913,R0914,R0915,R0917 --exit-zero
